### PR TITLE
Minimal API

### LINKED ISSUE #18: Simple API endpoint to query latest registered pets
For now this could be very simple and read-only I believe.
But as I would like it to not be a problem for resource usage in case of usage abuse, I think we need something to control the rate of requests.

### PR DESCRIPTION
**Pull request by cuducos**
Just implement the `/api/` endpoint listing all pets (fix #18).

### CODE REVIEW

**Comment by dirtycoder** [comment]
@cuducos looks great! Thanks!
Just a small observation, actually the `published` field is used to know if the pet was shared on Facebook.
(I should probably rename this field to make it clear)

**Comment by cuducos** [comment]
Hum… interesting! Gonna fix my code it and _amend_ the last commit, is that ok?

**Comment by dirtycoder** [comment]
Absolutely! Go on. :)

**Comment by cuducos** [comment]
Done in `336206f` (BTW I just added a simple comment in `pets/meupet/models.py` saying that `published` refers to Facebook, not to the site itself, is that ok)

**Comment by dirtycoder** [comment]
Looks good. :tada:

**Pull request merged**
